# SPDX-FileCopyrightText: 2022 Impulso Gov <contato@impulsogov.org>
#
# SPDX-License-Identifier: MIT


version: 2

models:
  - name: _configuracoes_estabelecimentos_ausentes_por_periodos
    description: >
      Identifica quais são as competências que não possuem registros 
      para cada combinação de município e estabelecimento, servindo 
      como tabela preliminar para o modelo final `configuracoes_estabelecimentos_ausentes_por_periodos`.
    config:
      grants:
        select: ['saude_mental_analistas', 'saude_mental_integracao']
      alias: _configuracoes_estabelecimentos_ausentes_por_periodos
      enabled: true
      indexes:
        - columns:
          - "id"
          unique: true
        - columns:
          - "unidade_geografica_id_sus"
          - "periodo_id"
          - "estabelecimento_id_scnes"
      materialized: table
      persist_docs:
        relation: true
      tags:
        - "saude_mental"
