impulso-saude-mental:
    target: analitico
    outputs:
      analitico:
        type: postgres

        # More information for the options in this file
        # can be found here: https://docs.getdbt.com/dbt-cli/configure-your-profile

        threads: 8
        # Additional Postgres options
        # Find out more about Postgres config options here:
        # https://docs.getdbt.com/reference/warehouse-profiles/postgres-profile

        dbname: principal
        schema: saude_mental

        # Set variable DBT_USER in your CI
        user: "{{ env_var('BD_ANALITICO_USUARIO') }}"

        # Set variable DBT_PASSWORD in your CI
        password: "{{ env_var('BD_ANALITICO_SENHA') }}"

        # Set variable DBT_REDSHIFT_ACCOUNT in your CI
        host: "{{ env_var('BD_ANALITICO_SERVIDOR') }}"

        port: 5432
        keepalives_idle: 0 # default 0, indicating the system default
        connect_timeout: 10 # default 10 seconds
        search_path: "$user, public, extensoes, postgis"

      producao:
        type: postgres

        # More information for the options in this file
        # can be found here: https://docs.getdbt.com/dbt-cli/configure-your-profile

        threads: 8
        # Additional Postgres options
        # Find out more about Postgres config options here:
        # https://docs.getdbt.com/reference/warehouse-profiles/postgres-profile

        dbname: postgres
        schema: saude_mental

        # Set variable DBT_USER in your CI
        user: "{{ env_var('BD_PRODUCAO_USUARIO') }}"

        # Set variable DBT_PASSWORD in your CI
        password: "{{ env_var('BD_PRODUCAO_SENHA') }}"

        # Set variable DBT_REDSHIFT_ACCOUNT in your CI
        host: "{{ env_var('BD_PRODUCAO_SERVIDOR') }}"

        port: 5432
        keepalives_idle: 0 # default 0, indicating the system default
        connect_timeout: 10 # default 10 seconds
