# For more information on this file, visit https://github.com/datacoves/dbt-coves

generate:
  sources:
    schemas:
      - RAW
    destination: "models/sources/{{ schema }}/{{ relation }}.sql"
    model_props_strategy: one_file_per_model
    # override default templates creating source_model_props.yml and source_model.sql under this folder
    templates_folder: "templates"
