# SPDX-FileCopyrightText: 2022 Impulso Gov <contato@impulsogov.org>
#
# SPDX-License-Identifier: MIT


repos:
# Comentado porque não funciona com dbt dockerizado.
# TODO: recriar funcionalidade com comandos locais
# - repo: https://github.com/offbi/pre-commit-dbt
  # rev: v1.0.0
  # hooks:
  # - id: dbt-compile
  # - id: check-source-table-has-description
  # - id: check-script-semicolon
  # - id: check-script-has-no-table-name
  # - id: check-script-ref-and-source
  # - id: check-model-has-properties-file
  # - id: check-model-has-description
  #   files: ^models/
  # Checar se arquivos atendem às especificações REUSE para padronização de
  # informações sobre licenças
- repo: https://github.com/fsfe/reuse-tool
  rev: v1.0.0
  hooks:
    - id: reuse
- repo: https://github.com/sqlfluff/sqlfluff
  rev: 1.4.5
  hooks:
    - id: sqlfluff-fix
    - id: sqlfluff-lint
