# SPDX-FileCopyrightText: 2022 Impulso Gov <contato@impulsogov.org>
#
# SPDX-License-Identifier: MIT


name: 'impulso_saude_mental'
version: '0.1.0'
config-version: 2

profile: 'impulso-saude-mental'

# Caminhos para pastas com recursos
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Caminhos para plugins, logs e arquivos compilados
packages-install-path: "dbt_packages"
log-path: "logs"
target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"

# Configuração dos modelos. Pode ser sobrescrito nos modelos específicos.
# Ver: https://docs.getdbt.com/docs/configuring-models
models:
  materialized: view
