# SPDX-FileCopyrightText: 2022 Impulso Gov <contato@impulsogov.org>
#
# SPDX-License-Identifier: MIT


impulso-saude-mental:

    target: analitico

    outputs:

      analitico:

        # Opções gerais. Ver:
        # https://docs.getdbt.com/dbt-cli/configure-your-profile
        type: postgres
        threads: 8

        # Opções do Postgres. Ver:
        # https://docs.getdbt.com/reference/warehouse-profiles/postgres-profile

        dbname: principal
        schema: saude_mental

        # Defina a variável DBT_ENV_SECRET_ANALITICO_SERVIDOR no GitHub Actions
        # e/ou no arquivo .env
        host: "{{ env_var('DBT_ENV_SECRET_ANALITICO_SERVIDOR') }}"
        port: 5432

        # Defina a variável DBT_ENV_SECRET_ANALITICO_USUARIO no GitHub Actions
        # e/ou no arquivo .env
        user: "{{ env_var('DBT_ENV_SECRET_ANALITICO_USUARIO') }}"

        # Defina DBT_ENV_SECRET_ANALITICO_SENHA no GitHub Actions
        # e/ou no arquivo .env
        password: "{{ env_var('DBT_ENV_SECRET_ANALITICO_SENHA') }}"

        keepalives_idle: 0 # default
        connect_timeout: 10 # default
        search_path: "$user, public, extensoes, postgis"

      producao:

        # Opções gerais. Ver:
        # https://docs.getdbt.com/dbt-cli/configure-your-profile
        type: postgres
        threads: 8

        # Opções do Postgres. Ver:
        # https://docs.getdbt.com/reference/warehouse-profiles/postgres-profile

        dbname: postgres
        schema: saude_mental

        # Defina a variável DBT_ENV_SECRET_PRODUCAO_SERVIDOR no GitHub Actions
        # e/ou no arquivo .env
        host: "{{ env_var('DBT_ENV_SECRET_PRODUCAO_SERVIDOR') }}"
        port: 5432

        # Defina a variável DBT_ENV_SECRET_PRODUCAO_USUARIO no GitHub Actions
        # e/ou no arquivo .env
        user: "{{ env_var('DBT_ENV_SECRET_PRODUCAO_USUARIO') }}"

        # Defina DBT_ENV_SECRET_PRODUCAO_SENHA no GitHub Actions
        # e/ou no arquivo .env
        password: "{{ env_var('DBT_ENV_SECRET_PRODUCAO_SENHA') }}"

        keepalives_idle: 0 # default 0, indicating the system default
        connect_timeout: 10 # default 10 seconds
