# SPDX-FileCopyrightText: 2022 Impulso Gov <contato@impulsogov.org>
#
# SPDX-License-Identifier: MIT


version: 2

models:
  - name: atendimentos
    description: >
      Atendimentos de profissionais de referência em saúde mental (psicólogos e
      psiquiatras) em estabelecimentos selecionados, conforme registrado em
      Boletins de Produção Ambulatorial individualizados (BPA-i), enviado ao
      Sistema de Informações Ambulatoriais do SUS (SIASUS) e disponibilizado
      pelo Departamento de Informática do SUS (DATASUS) em seu FTP público.
    config:
      alias: referencias_atendimentos
      enabled: true
      index:
        - columns:
          - "unidade_geografica_id"
          - "unidade_geografica_id_sus"
        - columns:
          - "realizacao_periodo_data_inicio"
        - columns:
          - "usuario_faixa_etaria"
        - columns:
          - "profissional_cns"
      materialized: incremental
      persist_docs:
        relation: true
      tags:
        - "saude_mental"
        - "referencias"
        - "bpa_i"
        - "incremental"
