# SPDX-FileCopyrightText: 2022 Impulso Gov <contato@impulsogov.org>
#
# SPDX-License-Identifier: MIT


name: Seed, Run, Check, Test and Docs

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Main CI
    runs-on: ubuntu-latest
    env:
      DBT_ENV_SECRET_ANALITICO_USUARIO: ${{ secrets.DBT_ENV_SECRET_ANALITICO_USUARIO }}
      DBT_ENV_SECRET_ANALITICO_SENHA: ${{ secrets.DBT_ENV_SECRET_ANALITICO_SENHA }}
      DBT_ENV_SECRET_ANALITICO_SERVIDOR: ${{ secrets.DBT_ENV_SECRET_ANALITICO_SERVIDOR }}
      DBT_ENV_SECRET_PRODUCAO_USUARIO: ${{ secrets.DBT_ENV_SECRET_PRODUCAO_USUARIO }}
      DBT_ENV_SECRET_PRODUCAO_SENHA: ${{ secrets.DBT_ENV_SECRET_PRODUCAO_SENHA }}
      DBT_ENV_SECRET_PRODUCAO_SERVIDOR: ${{ secrets.DBT_ENV_SECRET_PRODUCAO_SERVIDOR }}

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Baixar arquivo manifest do último disparo bem-sucedido
        uses: actions/download-artifact@v3
        with:
          name: manifest
          path: ./target/backup_manifest.json

      - name: Docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_SENHA: ${{secrets.DOCKER_SENHA}}
        run: docker login -u $DOCKER_USER -p $DOCKER_SENHA

      - name: Receber imagem Docker
        run: docker pull impulsogov/saude-mental-indicadores:latest

      - name: generate docs
        run: >
          docker run
          -e DBT_ENV_SECRET_ANALITICO_USUARIO
          -e DBT_ENV_SECRET_ANALITICO_SENHA
          -e DBT_ENV_SECRET_ANALITICO_SERVIDOR
          -e DBT_ENV_SECRET_PRODUCAO_USUARIO
          -e DBT_ENV_SECRET_PRODUCAO_SENHA
          -e DBT_ENV_SECRET_PRODUCAO_SERVIDOR
          --mount type=bind,source="$(pwd)/docs",destination="/usr/app/dbt/docs"
          impulsogov/saude-mental-indicadores:latest sh docs-gen.sh

      - name: deploy docs 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: docs

      - name: create UDFs
        run: >
          docker run
          -e DBT_ENV_SECRET_ANALITICO_USUARIO
          -e DBT_ENV_SECRET_ANALITICO_SENHA
          -e DBT_ENV_SECRET_ANALITICO_SERVIDOR
          -e DBT_ENV_SECRET_PRODUCAO_USUARIO
          -e DBT_ENV_SECRET_PRODUCAO_SENHA
          -e DBT_ENV_SECRET_PRODUCAO_SERVIDOR
          impulsogov/saude-mental-indicadores:latest dbt run-operation
          criar_udfs

      - name: Restituir arquivo manifest (1)
        shell: bash
        run: |
          cp ./target/backup_manifest.json ./target/manifest.json

      - name: seed
        run: >
          docker run
          -e DBT_ENV_SECRET_ANALITICO_USUARIO
          -e DBT_ENV_SECRET_ANALITICO_SENHA
          -e DBT_ENV_SECRET_ANALITICO_SERVIDOR
          -e DBT_ENV_SECRET_PRODUCAO_USUARIO
          -e DBT_ENV_SECRET_PRODUCAO_SENHA
          -e DBT_ENV_SECRET_PRODUCAO_SERVIDOR
          impulsogov/saude-mental-indicadores:latest dbt seed
          --select state:modified+ --full-refresh

      - name: Restituir arquivo manifest (2)
        shell: bash
        run: |
          cp ./target/backup_manifest.json ./target/manifest.json

      - name: dbt compile
        run: >
          docker run
          -e DBT_ENV_SECRET_ANALITICO_USUARIO
          -e DBT_ENV_SECRET_ANALITICO_SENHA
          -e DBT_ENV_SECRET_ANALITICO_SERVIDOR
          -e DBT_ENV_SECRET_PRODUCAO_USUARIO
          -e DBT_ENV_SECRET_PRODUCAO_SENHA
          -e DBT_ENV_SECRET_PRODUCAO_SERVIDOR
          impulsogov/saude-mental-indicadores:latest dbt compile
          --select state:modified+

      - name: Restituir arquivo manifest (3)
        shell: bash
        run: |
          cp ./target/backup_manifest.json ./target/manifest.json

      - name: dbt run
        run: >
          docker run
          -e DBT_ENV_SECRET_ANALITICO_USUARIO
          -e DBT_ENV_SECRET_ANALITICO_SENHA
          -e DBT_ENV_SECRET_ANALITICO_SERVIDOR
          -e DBT_ENV_SECRET_PRODUCAO_USUARIO
          -e DBT_ENV_SECRET_PRODUCAO_SENHA
          -e DBT_ENV_SECRET_PRODUCAO_SERVIDOR
          impulsogov/saude-mental-indicadores:latest dbt run
          --select state:modified+ --full-refresh

      - name: Restituir arquivo manifest (4)
        shell: bash
        run: |
          cp ./target/backup_manifest.json ./target/manifest.json

      - name: test
        run: >
          docker run
          -e DBT_ENV_SECRET_ANALITICO_USUARIO
          -e DBT_ENV_SECRET_ANALITICO_SENHA
          -e DBT_ENV_SECRET_ANALITICO_SERVIDOR
          -e DBT_ENV_SECRET_PRODUCAO_USUARIO
          -e DBT_ENV_SECRET_PRODUCAO_SENHA
          -e DBT_ENV_SECRET_PRODUCAO_SERVIDOR
          impulsogov/saude-mental-indicadores:latest dbt test
          --select state:modified+

      - name: Gravar arquivo manifest da execução bem-sucedida
        uses: actions/upload-artifact@v3
        with:
          name: manifest
          path: ./target/manifest.json
